name: Auto deployment testing v2

on:
  push:
    branches:
      [test-branch]
    paths:
    - '**'
    - ".github/workflows/test-deploy-action"
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@e5ee24264226bfb6878b5e062a520b990d664efd
        with:
          appSourcePath: ${{ github.workspace }} 
          acrName: actiondebugregistry
          containerAppName: debug-capp
          resourceGroup: PatcherTestRg
          ingress: external
          targetPort: 8080
          imageToBuild: actiondebugregistry.azurecr.io/test:v3