name: Trigger auto deployment for test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ test-branch ]
    paths:
    - '**'
    - '.github/workflows/test-app-AutoDeployTrigger-32dabacf-fe4f-416c-9f4b-56ae00c681f9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTAPP_REGISTRY_PASSWORD }}
          containerAppName: test-app
          resourceGroup: PatcherTestRg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


