name: Trigger auto deployment for test-app-eus-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ test-branch ]
    paths:
    - '**'
    - '.github/workflows/test-app-eus-2-AutoDeployTrigger-a899af3c-1266-4493-8dc7-1e6f154e7fef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTAPPEUS2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTAPPEUS2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTAPPEUS2_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions

      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{github.workspace}}/azure-cli-extensions/containerapp-0.3.50-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTAPPEUS2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTAPPEUS2_REGISTRY_PASSWORD }}
          containerAppName: test-app-eus-2
          resourceGroup: ca-harrli-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


